title: Alan Al Yussef
logo: images/mypic_frame.png
description: Doctoral researcher and pedagogical staff @ [APEC-Vrije Universiteit Brussel](https://researchportal.vub.be/en/persons/alan-al-yussef)

theme: jekyll-theme-minimal


